name: CI build and push for cv-microservice-info docker image

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decrypt and write .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" | base64 --decode > .env

      - name: Build cv-microservice-info image
        env:
          IMAGE_TAG: ${{ github.event.release.tag_name }}
          REPO_NAME: ${{ github.repository }}
        run: |
          echo "Building cv-microservice-info image with tag $IMAGE_TAG"
          REPO_NAME_LOWER=$(echo $REPO_NAME | tr '[:upper:]' '[:lower:]')
          docker build --tag ghcr.io/$REPO_NAME_LOWER:$IMAGE_TAG .

      - name: Push cv-microservice-info image
        env:
          IMAGE_TAG: ${{ github.event.release.tag_name }}
          REPO_NAME: ${{ github.repository }}
        run: | 
          echo "Pushing cv-microservice-info image with tag $IMAGE_TAG"
          REPO_NAME_LOWER=$(echo $REPO_NAME | tr '[:upper:]' '[:lower:]')
          echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/$REPO_NAME_LOWER:$IMAGE_TAG
          docker logout ghcr.io